language: python
dist: xenial
sudo: true

python:
  - 3.8

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync -d
  - cp contrib/env-sample .env

#before_script:
#  - psql -c "CREATE DATABASE testdb;" -U postgres -W
#
script:
#  - pipenv run flake8 .
  - pipenv run pytest --cov=apps

#after_success:
#  - pipenv run codecov