version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2020!"
    ports:
      - "5432:5432"
    volumes:
      - /home/mod/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "mod64bits@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2020!"
    ports:
      - "8080:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge